### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by xy-hong** [xy-hong/pixi-chess#2]
- [ ] Highlight last move
- [ ] Add capture feature
- [ ] Promotion feature
- [ ] Scaleable chess board
- [ ] Show pgn info next to the board
- [ ] Undo move feature
- [ ] 10 min countdown for each player
